### PR TITLE
Fixing bug in spinnaker 2.x.x which causes serial number to be read in…

### LINKED ISSUE #76: Cannot detect Camera
***System Description***
Spinnaker Version: **spinnaker-2.0.0.109-amd64**
ROS Version: **Kinetic**

***Computer details***
Processor: Intel® Core™ i5-7200U CPU @ 2.50GHz × 4 
RAM: 15,5 GiB

Cameras work with **SpinView**

**Bug**
The package is built up successfully but while running the command it is not working by saying that camera is not detected and camera id is not in the config list.
```
roslaunch spinnaker_sdk_camera_driver acquisition.launch
```

**Error Messages**
Giving me the following error message --
```
[ WARN] [1586515189.562547025]:    Camera 18522234 not detected!!!
[FATAL] [1586515189.562635898]: ASSERTION FAILED
	file = /home/atif/spinnaker_ws/src/spinnaker_sdk_camera_driver/src/capture.cpp
	line = 317
	cond = cams.size()
	message = 
[FATAL] [1586515189.562889674]: None of the connected cameras are in the config list!
[FATAL] [1586515189.562956459]: 

[FATAL] [1586515189.713728360]: Failed to load nodelet '/acquisition_node` of type `acquisition/capture_nodelet` to manager `vision_nodelet_manager'
[vision_nodelet_manager-2] process has died [pid 6468, exit code -5, cmd /opt/ros/kinetic/lib/nodelet/nodelet manager __name:=vision_nodelet_manager __log:=/home/atif/.ros/log/98d89c82-7b17-11ea-b98a-88d7f69a3204/vision_nodelet_manager-2.log].
log file: /home/atif/.ros/log/98d89c82-7b17-11ea-b98a-88d7f69a3204/vision_nodelet_manager-2*.log
[acquisition_node-3] process has died [pid 6469, exit code 255, cmd /opt/ros/kinetic/lib/nodelet/nodelet load acquisition/capture_nodelet vision_nodelet_manager __name:=acquisition_node __log:=/home/atif/.ros/log/98d89c82-7b17-11ea-b98a-88d7f69a3204/acquisition_node-3.log].
log file: /home/atif/.ros/log/98d89c82-7b17-11ea-b98a-88d7f69a3204/acquisition_node-3*.log

```
**Steps were taken**

I have gone into the file ```params/test_params.yaml``` and changed the first few lines:
```
cam_ids:
- 18522234
cam_aliases:
- cam0
master_cam: 18522234
```

**Information Screenshots**

I have changed the **cam_ids** and **master_cam** by using the information of the following images

Image

and

Image1

### LINKED ISSUE #80: Spinnaker: GenICam::AccessException= Node is not writable
**System Description**
Camera Name and Model: Blackfly S USB 3 BFLY-U3-23S6C-C
Operating System: Ubuntu 18.04 LTS
Spinnaker Version: 1.27.0.48
ROS Version: melodic

***Computer details***
Processor: ARMv8 64-bit CPU 
RAM: 8GB

***Multiple Cameras Only***
Single Camera

**Do the cameras work with SpinView?**
Yes

**Describe the bug**
While launching the acquisition node or nodelet the driver try to write to locked node of the camera. 
Every time tried to write a locked node this error occurs. Not only AutoExposureTargetGreyValueAuto, but also BinningHorizontal and similar.

As described in ([Feature Locking in Spinnaker API](https://www.flir.de/support-center/iis/machine-vision/application-note/feature-locking-in-spinnaker-api/)) there are states in which nodes are dependent on another and therefore locked.

Would be great to check whether the node ist locked or not before trying to write to. 

**Error Messages**
mue@mue-tx2:~/catkin_ws$ roslaunch spinnaker_sdk_camera_driver acquisition_node.launch
... logging to /home/mue/.ros/log/88957556-8301-11ea-9be7-00044bf67fa2/roslaunch-mue-tx2-9241.log
Checking log directory for disk usage. This may take a while.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

started roslaunch server http://mue-tx2:36783/

SUMMARY
========

PARAMETERS
 * /acquisition_node/binning: 1
 * /acquisition_node/cam_aliases: ['cam0']
 * /acquisition_node/cam_ids: [20086912]
 * /acquisition_node/color: False
 * /acquisition_node/delay: 1.0
 * /acquisition_node/distortion_coeffs: [[-0.021141875266...
 * /acquisition_node/distortion_model: plumb_bob
 * /acquisition_node/exposure_time: 0
 * /acquisition_node/frames: 3400
 * /acquisition_node/image_height: 1536
 * /acquisition_node/image_width: 2048
 * /acquisition_node/intrinsic_coeffs: [[1886.9232141485...
 * /acquisition_node/live: False
 * /acquisition_node/live_grid: False
 * /acquisition_node/master_cam: 20086912
 * /acquisition_node/max_rate_save: False
 * /acquisition_node/projection_coeffs: [[913.700317, 0.0...
 * /acquisition_node/rectification_coeffs: [[1.0, 0.0, 0.0, ...
 * /acquisition_node/save: False
 * /acquisition_node/save_path: ~
 * /acquisition_node/save_type: bmp
 * /acquisition_node/skip: 20
 * /acquisition_node/soft_framerate: 20
 * /acquisition_node/target_grey_value: 0
 * /acquisition_node/time: False
 * /acquisition_node/to_ros: True
 * /acquisition_node/utstamps: False
 * /rosdistro: melodic
 * /rosversion: 1.14.5

NODES
  /
    acquisition_node (spinnaker_sdk_camera_driver/acquisition_node)

auto-starting new master
process[master]: started with pid [9251]
ROS_MASTER_URI=http://localhost:11311

setting /run_id to 88957556-8301-11ea-9be7-00044bf67fa2
process[rosout-1]: started with pid [9262]
started core service [/rosout]
process[acquisition_node-2]: started with pid [9269]
[ INFO] [1587385323.966521931]: [ OK ] USB memory: 1000 MB
[ INFO] [1587385323.971143543]: *** PARAMETER SETTINGS ***
[ INFO] [1587385323.971262522]: ** Date = 20200420
[ INFO] [1587385323.974745899]:   Save path set via parameter to: /home/mue
[ INFO] [1587385323.974890671]:   Camera IDs:
[ INFO] [1587385323.976844956]:     20086912
[ INFO] [1587385323.979509019]:   Camera Aliases:
[ INFO] [1587385323.979602173]:     20086912 >> cam0
[ INFO] [1587385323.982472320]:   Unique time stamps for each camera: false
[ INFO] [1587385323.984481999]:   color set to: false
[ INFO] [1587385323.985964306]:   Exporting images to ROS: true
[ INFO] [1587385323.987357746]:   Showing live images setting: false
[ INFO] [1587385323.989271327]:   Showing grid-style live images setting: false
[ INFO] [1587385323.991431762]:   Max Rate Save Mode: false
[ INFO] [1587385323.993438881]:   Displaying timing details: false
[ INFO] [1587385323.994868450]:   No. of images to skip set to: 20
[ INFO] [1587385323.996258467]:   Init sleep delays set to : 1.00 sec
[ WARN] [1587385323.997582786]:   'fps' Parameter not set, using default behavior: fps=20.00
[ INFO] [1587385323.999158630]:   'exposure_time'=0, Setting autoexposure
[ INFO] [1587385324.000729387]:   'target_grey_value'=0, Setting AutoExposureTargetGreyValueAuto to Continuous/ auto
[ INFO] [1587385324.002276175]:   Binning set to: 1
[ INFO] [1587385324.004456002]:   Using Software rate control, rate set to: 20
[ INFO] [1587385324.005551260]:   Saving images set to: 0
[ INFO] [1587385324.007456264]:   Camera Intrinsic Paramters:
[ INFO] [1587385324.008027509]:    1886.923214 0.000000 604.721488 0.000000 1886.666877 493.477267 0.000000 0.000000 1.000000 
[ INFO] [1587385324.009729341]:   Camera Distortion Paramters:
[ INFO] [1587385324.009921794]:    -0.021142 -0.373387 2.385983 3.282457 
[ INFO] [1587385324.011236672]:   Camera Rectification Paramters:
[ INFO] [1587385324.011449061]:    1.000000 0.000000 0.000000 0.000000 1.000000 0.000000 0.000000 0.000000 1.000000 
[ INFO] [1587385324.012874278]:   Camera Projection Paramters:
[ INFO] [1587385324.013090859]:    913.700317 0.000000 953.448302 0.000000 0.000000 1063.296631 777.871993 0.000000 0.000000 0.000000 1.000000 0.000000 
[ INFO] [1587385324.013162829]:   Camera coeffs provided, camera info messges will be published.
[ INFO] [1587385324.013304336]: Creating system instance...
[ INFO] [1587385324.019511393]: Retreiving list of cameras...
[ INFO] [1587385325.741552831]: Numer of cameras found: 1
[ INFO] [1587385325.744269950]:  Cameras connected: 1
[ INFO] [1587385325.744604038]:   -20086912
[ INFO] [1587385325.788993771]: Dynamic Reconfigure: Level : 4294967295
[ INFO] [1587385325.794768177]: *** FLUSH SEQUENCE ***
[ INFO] [1587385325.794912020]: Initializing cameras...
[ INFO] [1587385326.235905354]: Deinitializing cameras...
[ INFO] [1587385326.278255771]: All cameras deinitialized.
[ INFO] [1587385328.279726905]: Initializing cameras...
[FATAL] [1587385328.534330325]: Unable to set AutoExposureTargetGreyValueAuto to Continuous (enum retrieval). Aborting...
[FATAL] [1587385328.534636700]: Error: Spinnaker: LogicalErrorException NULL pointer dereferenced [-2005]
[ WARN] [1587385328.534728286]: Most likely cause for this error is if your camera can't support color and your are trying to set it to color mode
terminate called after throwing an instance of 'Spinnaker::Exception'
  what():  Spinnaker: GenICam::AccessException= Node is not writable. : AccessException thrown in node 'TriggerSoftware' while calling 'TriggerSoftware.Execute()' (file 'CommandT.h', line 61) [-2006]
[acquisition_node-2] process has died [pid 9269, exit code -6, cmd /home/mue/catkin_ws/devel/lib/spinnaker_sdk_camera_driver/acquisition_node __name:=acquisition_node __log:=/home/mue/.ros/log/88957556-8301-11ea-9be7-00044bf67fa2/acquisition_node-2.log].
log file: /home/mue/.ros/log/88957556-8301-11ea-9be7-00044bf67fa2/acquisition_node-2*.log

**Screenshots**

### PR DESCRIPTION
**Pull request by shahvi**
… hex
Fixes #76

### CODE REVIEW

**Comment by mithunvarma** [comment]
I tested it with 1.13.0.31, works.
@abhishekbajpayee did you test with spinnaker sdk 2.x.x  ?
thanks

**Comment by soulslicer** [comment]
> I tested it with 1.13.0.31, works.
> @abhishekbajpayee did you test with spinnaker sdk 2.x.x ?
> thanks

Not working

**Comment by abhishekbajpayee** [comment]
@mithunvarma did you guys recently port this code over to Github? Just wondering how this shows I pushed a commit 18 days back :-)

**Comment by shahvi** [comment]
@abhishekbajpayee I pushed a commit from the server on the car and it had your details saved on it.

**Pull request merged**
